### ISSUE TITLE
.generate_data() method

### ISSUE THREAD

**Issue by RunoWazlib** [RunoWazlib/mbholm_ad_dev#1]
It is unclear at this moment if .generate_data() makes new data every time it is called

Called at L9, L19, L39 on 6/23/2023

**Comment by LuiseSchwenke** [comment]
Hey, yes it generates new values every time it get's called. If you want random numbers but with the same shuffled split every time  it get's called, I guess you could simply add random_state as a parameter to the .generate_data() function like this: 
X_train, _, _, _ = pyod.utils.data.generate_data(n_train=samples, n_features=features, contamination=contamination, random_state=42)

**Comment by RunoWazlib** [comment]
Entering a random_state to .generate_data() seems to have fixed the problem, updated on main. Thanks @LuiseSchwenke!
